# NAME            : Local
# AUTHOR          : JY-Mar
# REPO            : https://github.com/JY-Mar/PxyRes
# UPDATED         : 2026-04-28 14:15:36 GMT+8
# GEOIP           : 1
# TOTAL           : 1

payload:
  # 内网全直连
  - GEOIP,LAN,no-resolve
